-- -----------------------------------------------
-- DLL ANSI (Padrao)
-- -----------------------------------------------
-- OBS: CASO NAO EXISTA, CRIAR O SCHEMA cnpj

-- -----------------------------------------------
-- 1. TABELAS AUXILIARES
-- -----------------------------------------------
-- 1.1. CNAE
-- 1.2. MOTIVO_SITUACAO_CADASTRAL
-- 1.3. MUNICIPIO
-- 1.4. NATUREZA_JURIDICA
-- 1.5. PAIS
-- 1.6. QUALIFICACAO_SOCIO
-- -----------------------------------------------
CREATE TABLE cnpj.CNAE (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_CNAE PRIMARY KEY (CODIGO)
);

CREATE TABLE cnpj.MOTIVO_SITUACAO_CADASTRAL (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_MOTI PRIMARY KEY (CODIGO)
);

CREATE TABLE cnpj.MUNICIPIO (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_MUNI PRIMARY KEY (CODIGO)
);

CREATE TABLE cnpj.NATUREZA_JURIDICA (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_NATJ PRIMARY KEY (CODIGO)
);

CREATE TABLE cnpj.PAIS (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_PAIS PRIMARY KEY (CODIGO)
);
-- LISTA DE PAISES DO SISCOMEX (http://www.siscomex.gov.br)
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (13, 'Afeganistão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (17, 'Albânia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (23, 'Alemanha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (31, 'Burkina Faso', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (37, 'Andorra', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (40, 'Angola', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (41, 'Anguilla', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (43, 'Antigua E Barbuda', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (47, 'Antilhas Holandesas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (53, 'Arábia Saudita', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (59, 'Argélia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (63, 'Argentina', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (64, 'Armênia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (65, 'Aruba', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (69, 'Austrália', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (72, 'Áustria', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (73, 'Azerbaijão, República do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (77, 'Bahamas, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (80, 'Bahrein, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (81, 'Bangladesh', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (83, 'Barbados', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (85, 'Belarus, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (87, 'Bélgica', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (88, 'Belize', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (90, 'Bermudas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (93, 'Mianmar (Birmânia)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (97, 'Bolívia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (98, 'Bosnia-Herzegovina (República da)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (101, 'Botsuana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (108, 'Brunei', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (111, 'Bulgária, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (115, 'Burundi', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (119, 'Butão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (127, 'Cabo Verde, República de', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (137, 'Cayman, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (141, 'Camboja', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (145, 'Camarões', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (149, 'Canadá', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (150, 'Jersey, Ilha do Canal', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (151, 'Canárias, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (153, 'Cazaquistao, República do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (154, 'Catar', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (158, 'Chile', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (160, 'China, República Popular', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (161, 'Formosa (Taiwan)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (163, 'Chipre', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (165, 'Cocos-Keeling, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (169, 'Colômbia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (173, 'Comores, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (177, 'Congo', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (183, 'Cook, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (187, 'Coréia, Rep.Pop.Democrática', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (190, 'Coréia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (193, 'Costa do Marfim', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (195, 'Croácia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (196, 'Costa Rica', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (198, 'Coveite', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (199, 'Cuba', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (229, 'Benin', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (232, 'Dinamarca', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (235, 'Dominica, Ilha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (239, 'Equador', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (240, 'Egito', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (243, 'Eritreia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (244, 'Emirados Árabes Unidos', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (245, 'Espanha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (246, 'Eslovênia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (247, 'Eslovaca, República', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (249, 'Estados Unidos', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (251, 'Estônia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (253, 'Etiópia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (255, 'Falkland (Ilhas Malvinas)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (259, 'Feroe, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (267, 'Filipinas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (271, 'Finlândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (275, 'França', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (281, 'Gabão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (285, 'Gambia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (289, 'Gana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (291, 'Geórgia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (293, 'Gibraltar', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (297, 'Granada', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (301, 'Grécia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (305, 'Groenlândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (309, 'Guadalupe', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (313, 'Guam', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (317, 'Guatemala', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (325, 'Guiana Francesa', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (329, 'Guiné', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (331, 'Guiné-Equatorial', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (334, 'Guiné-Bissau', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (337, 'Guiana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (341, 'Haiti', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (345, 'Honduras', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (351, 'Hong Kong', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (355, 'Hungria, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (357, 'Iemen', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (359, 'Man, Ilha de', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (361, 'Índia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (365, 'Indonésia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (369, 'Iraque', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (372, 'Irã, República Islâmica do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (375, 'Irlanda', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (379, 'Islândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (383, 'Israel', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (386, 'Itália', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (391, 'Jamaica', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (396, 'Johnston, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (399, 'Japão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (403, 'Jordânia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (411, 'Kiribati', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (420, 'Laos, Rep.Pop.Democr.do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (423, 'Lebuan, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (426, 'Lesoto', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (427, 'Letônia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (431, 'Líbano', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (434, 'Libéria', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (438, 'Líbia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (440, 'Liechtenstein', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (442, 'Lituânia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (445, 'Luxemburgo', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (447, 'Macau', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (449, 'Macedônia, Ant.Rep.Iugoslava', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (450, 'Madagascar', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (452, 'Madeira, Ilha da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (455, 'Malásia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (458, 'Malavi', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (461, 'Maldivas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (464, 'Mali', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (467, 'Malta', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (472, 'Marianas do Norte', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (474, 'Marrocos', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (476, 'Marshall, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (477, 'Martinica', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (485, 'Maurício', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (488, 'Mauritânia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (490, 'Midway, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (493, 'México', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (494, 'Moldavia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (495, 'Mônaco', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (497, 'Mongólia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (498, 'Montenegro', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (499, 'Micronésia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (501, 'Montserrat, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (505, 'Moçambique', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (507, 'Namíbia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (508, 'Nauru', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (511, 'Christmas,Ilhas (Navidad)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (517, 'Nepal', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (521, 'Nicarágua', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (525, 'Niger', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (528, 'Nigéria', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (531, 'Niue, Ilha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (535, 'Norfolk, Ilha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (538, 'Noruega', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (542, 'Nova Caledônia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (545, 'Papua Nova Guiné', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (548, 'Nova Zelândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (551, 'Vanuatu', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (556, 'Omã', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (566, 'Pacífico, Ilhas do (possessão dos EUA)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (573, 'Países Baixos (Holanda)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (575, 'Palau', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (576, 'Paquistão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (580, 'Panamá', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (586, 'Paraguai', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (589, 'Peru', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (593, 'Pitcairn, Ilha De', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (599, 'Polinésia Francesa', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (603, 'Polônia, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (607, 'Portugal', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (611, 'Porto Rico', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (623, 'Quênia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (625, 'Quirguiz, República da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (628, 'Reino Unido', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (640, 'República Centro-Africana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (647, 'República Dominicana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (660, 'Reunião, Ilha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (665, 'Zimbabue', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (670, 'Romênia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (675, 'Ruanda', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (676, 'Rússia, Federação da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (677, 'Salomão, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (678, 'Saint Kitts e Nevis', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (685, 'Saara Ocidental', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (687, 'El Salvador', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (690, 'Samoa', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (691, 'Samoa Americana', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (695, 'São Cristovão e Neves, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (697, 'San Marino', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (700, 'São Pedro e Miquelon', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (705, 'São Vicente e Granadinas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (710, 'Santa Helena', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (715, 'Santa Lúcia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (720, 'São Tomé e Príncipe, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (728, 'Senegal', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (731, 'Seychelles', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (735, 'Serra Leoa', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (737, 'Servia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (741, 'Singapura', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (744, 'Síria, República Árabe da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (748, 'Somália', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (750, 'Sri Lanka', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (754, 'Suazilândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (756, 'África do Sul', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (759, 'Sudão', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (764, 'Suécia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (767, 'Suíça', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (770, 'Suriname', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (772, 'Tadjiquistão, República do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (776, 'Tailândia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (780, 'Tanzania, Rep. Unida da', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (782, 'Território Britânico no Oceano Índico', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (783, 'Djibuti', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (788, 'Chade', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (791, 'Tcheca, República', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (795, 'Timor Leste', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (800, 'Togo', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (805, 'Toquelau, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (810, 'Tonga', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (815, 'Trinidad e Tobago', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (820, 'Tunísia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (823, 'Turcas e Caicos, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (824, 'Turcomenistão, República do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (827, 'Turquia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (828, 'Tuvalu', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (831, 'Ucrânia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (833, 'Uganda', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (845, 'Uruguai', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (847, 'Uzbequistão, República do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (848, 'Vaticano, Est. da Cidade do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (850, 'Venezuela', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (858, 'Vietnã', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (863, 'Virgens, Ilhas (Britânicas)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (866, 'Virgens, Ilhas (E.U.A.)', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (870, 'Fiji', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (873, 'Wake, Ilha', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (875, 'Wallis e Futuna, Ilhas', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (888, 'Congo, República Democrática do', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (890, 'Zâmbia', 0);
INSERT INTO cnpj.PAIS (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (998, 'Delegação Especial da Palestina', 0);

CREATE TABLE cnpj.QUALIFICACAO_SOCIO (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,
	CONSTRAINT PK_QUAL PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'Acionista', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, 'Acionista Controlador', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, 'Acionista Diretor', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (4, 'Acionista Presidente', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (5, 'Administrador ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (6, 'Administradora de consórcio de Empresas ou Grupo de Empresas', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (7, 'Comissário', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (8, 'Conselheiro de Administração', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (9, 'Curador ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (10, 'Diretor ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (11, 'Interventor ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (12, 'Inventariante ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (13, 'Liquidante ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (14, 'Mãe ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (15, 'Pai ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (16, 'Presidente ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (17, 'Procurador ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (18, 'Secretário', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (19, 'Síndico (Condomínio) ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (20, 'Sociedade Consorciada ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (21, 'Sociedade Filiada ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (22, 'Sócio', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (23, 'Sócio Capitalista ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (24, 'Sócio Comanditado ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (25, 'Sócio Comanditário ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (26, 'Sócio de Indústria ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (27, 'Sócio Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (28, 'Sócio-Gerente ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (29, 'Sócio ou Acionista Incapaz ou Relativamente Incapaz (exceto menor) ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (30, 'Sócio ou Acionista Menor (Assistido/Representado) ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (31, 'Sócio Ostensivo ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (32, 'Tabelião ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (33, 'Tesoureiro', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (34, 'Titular de Empresa Individual Imobiliária ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (35, 'Tutor ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (36, 'Gerente-Delegado', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (37, 'Sócio Pessoa Jurídica Domiciliado no Exterior ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (38, 'Sócio Pessoa Física Residente ou Domiciliado no Exterior ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (39, 'Diplomata ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (40, 'Cônsul ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (41, 'Representante de Organização Internacional ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (42, 'Oficial de Registro ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (43, 'Responsável ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (44, 'Sócio Participante', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (45, 'Sócio Investidor', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (46, 'Ministro de Estado das Relações Exteriores ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (47, 'Sócio Pessoa Física Residente no Brasil ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (48, 'Sócio Pessoa Jurídica Domiciliado no Brasil ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (49, 'Sócio-Administrador ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (50, 'Empresário ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (51, 'Candidato a Cargo Político Eletivo ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (52, 'Sócio com Capital ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (53, 'Sócio sem Capital ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (54, 'Fundador ', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (55, 'Sócio Comanditado Residente no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (56, 'Sócio Comanditário Pessoa Física Residente no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (57, 'Sócio Comanditário Pessoa Jurídica Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (58, 'Sócio Comanditário Incapaz', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (59, 'Produtor Rural', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (60, 'Cônsul Honorário', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (61, 'Responsável Indigena', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (62, 'Representante das Instituições Extraterritoriais', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (63, 'Cotas em Tesouraria', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (64, 'Administrador Judicial', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (65, 'Titular Pessoa Física Residente ou Domiciliado no Brasil', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (66, 'Titular Pessoa Física Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (67, 'Titular Pessoa Física Incapaz ou Relativamente Incapaz (exceto menor)', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (68, 'Titular Pessoa Física Menor (Assistido/Representado)', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (69, 'Beneficiário Final', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (70, 'Administrador Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (71, 'Conselheiro de Administração Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (72, 'Diretor Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (73, 'Presidente Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (74, 'Sócio-Administrador Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (75, 'Fundador Residente ou Domiciliado no Exterior', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (76, 'Protetor', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (77, 'Vice-Presidente', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (78, 'Titular Pessoa Jurídica Domiciliada no Brasil', 0);
INSERT INTO cnpj.QUALIFICACAO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (79, 'Titular Pessoa Jurídica Domiciliada no Exterior', 0);

-- -----------------------------------------------
-- 2. EMPRESA
-- -----------------------------------------------
-- 2.0. EMPRESA
-- 2.1. PORTE_EMPRESA
-- 2.2. PORTE_EMPRESA_LAYOUT_ANTIGO
-- -----------------------------------------------
CREATE TABLE cnpj.PORTE_EMPRESA (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_PORT PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.PORTE_EMPRESA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'NÃO INFORMADO', 0);
INSERT INTO cnpj.PORTE_EMPRESA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, 'MICRO EMPRESA', 0);
INSERT INTO cnpj.PORTE_EMPRESA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, 'EMPRESA DE PEQUENO PORTE', 0);
INSERT INTO cnpj.PORTE_EMPRESA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (5, 'DEMAIS', 0);

CREATE TABLE cnpj.PORTE_EMPRESA_LAYOUT_ANTIGO (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	
	CONSTRAINT PK_PORT_ANTIGO PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.PORTE_EMPRESA_LAYOUT_ANTIGO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (0, 'NÃO INFORMADO', 0);
INSERT INTO cnpj.PORTE_EMPRESA_LAYOUT_ANTIGO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'MICRO EMPRESA', 0);
INSERT INTO cnpj.PORTE_EMPRESA_LAYOUT_ANTIGO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, 'EMPRESA DE PEQUENO PORTE', 0);
INSERT INTO cnpj.PORTE_EMPRESA_LAYOUT_ANTIGO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (5, 'DEMAIS', 0);

CREATE TABLE cnpj.EMPRESA (
	CNPJ_BASICO CHAR(8) NOT NULL,
	RAZAO_SOCIAL VARCHAR(255) NOT NULL,
	COD_NATUREZA_JURIDICA INTEGER NOT NULL,
	COD_QUALIFICACAO_RESPONSAVEL INTEGER NOT NULL,
	CAPITAL_SOCIAL DECIMAL(20, 2) NOT NULL,
	COD_PORTE INTEGER NULL,
	ENTE_FEDERATIVO_RESPONSAVEL VARCHAR(255) NULL,
	CONSTRAINT PK_EMPR PRIMARY KEY (CNPJ_BASICO),
	CONSTRAINT FK_NATJ_EMPR FOREIGN KEY (COD_NATUREZA_JURIDICA) REFERENCES cnpj.NATUREZA_JURIDICA (CODIGO),
	CONSTRAINT FK_QUAL_EMPR_RESP FOREIGN KEY (COD_QUALIFICACAO_RESPONSAVEL) REFERENCES cnpj.QUALIFICACAO_SOCIO (CODIGO),
	CONSTRAINT FK_PORT_EMPR FOREIGN KEY (COD_PORTE) REFERENCES cnpj.PORTE_EMPRESA (CODIGO)
);

-- -----------------------------------------------
-- 3. SOCIO
-- -----------------------------------------------
-- 3.0. SOCIO
-- 3.1. TIPO_SOCIO
-- 3.2. FAIXA_ETARIA
-- -----------------------------------------------
CREATE TABLE cnpj.TIPO_SOCIO (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL, 
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL,	 	
	CONSTRAINT PK_TISO PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.TIPO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'PESSOA JURÍDICA', 0);
INSERT INTO cnpj.TIPO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, 'PESSOA FÍSICA', 0);
INSERT INTO cnpj.TIPO_SOCIO (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, 'ESTRANGEIRO', 0);

CREATE TABLE cnpj.FAIXA_ETARIA (
	CODIGO INTEGER NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL, 
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL, 
	CONSTRAINT PK_FAET PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (0, 'NÃO SE APLICA', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, '0 A 12 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, '13 A 20 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, '21 A 30 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (4, '31 A 40 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (5, '41 A 50 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (6, '51 A 60 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (7, '61 A 70 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (8, '71 A 80 ANOS', 0);
INSERT INTO cnpj.FAIXA_ETARIA (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (9, 'MAIOR DE 80 ANOS', 0);

CREATE TABLE cnpj.SOCIO (
	CNPJ_BASICO CHAR(8) NOT NULL,
	COD_TIPO INTEGER NOT NULL, 
	NOME VARCHAR(255) NOT NULL,
	CNPJ_CPF VARCHAR(14) NOT NULL,
	COD_QUALIFICACAO INTEGER NOT NULL, 
	DATA_ENTRADA_SOCIEDADE CHAR(8) NOT NULL,
	COD_PAIS INTEGER NULL, 
	CPF_REPRESENTANTE CHAR(11) NULL,
	NOME_REPRESENTANTE VARCHAR(255) NULL,
	COD_QUALIFICACAO_REPRESENTANTE INTEGER NULL, 
	COD_FAIXA_ETARIA INTEGER NOT NULL,
	CONSTRAINT FK_EMPR_SOCI FOREIGN KEY (CNPJ_BASICO) REFERENCES cnpj.EMPRESA (CNPJ_BASICO),
	CONSTRAINT FK_TISO_SOCI FOREIGN KEY (COD_TIPO) REFERENCES cnpj.TIPO_SOCIO (CODIGO),
	CONSTRAINT FK_QUAL_SOCI FOREIGN KEY (COD_QUALIFICACAO) REFERENCES cnpj.QUALIFICACAO_SOCIO (CODIGO), 
	CONSTRAINT FK_QUAL_SOCI_REPR FOREIGN KEY (COD_QUALIFICACAO_REPRESENTANTE) REFERENCES cnpj.QUALIFICACAO_SOCIO (CODIGO),
	CONSTRAINT FK_FAET_SOCI FOREIGN KEY (COD_FAIXA_ETARIA) REFERENCES cnpj.FAIXA_ETARIA (CODIGO)
);
-- OBS1: 
-- REMOVIDA: CONSTRAINT PK_SOCI PRIMARY KEY (CNPJ_BASICO, COD_TIPO, NOME, CNPJ_CPF)
-- MOTIVO: CASOS DE REPETICAO PARA COD_TIPO = 3 (ESTRANGEIRO)
-- SUGESTAO: Se SGBD possibilitar, criar uma coluna CODIGO autoincrementavel e utiliza-la como PRIMARY KEY
-- Ex (mssqlserver):
--	CODIGO INTEGER NOT NULL IDENTITY(1,1),
-- 	CONSTRAINT PK_SOCI PRIMARY KEY (CODIGO),

-- OBS2:
-- REMOVIDA: CONSTRAINT FK_PAIS_SOCI FOREIGN KEY (COD_PAIS) REFERENCES cnpj.PAIS (CODIGO)
-- MOTIVO: CODIGOS SEM CORRESPONDÊNCIA NA LISTA DE PAISES DO SISCOMEX (http://www.siscomex.gov.br)

-- -----------------------------------------------
-- 4. SIMPLES
-- -----------------------------------------------
-- 4.0. SIMPLES
-- -----------------------------------------------
CREATE TABLE cnpj.SIMPLES (
	CNPJ_BASICO CHAR(8) NOT NULL,
	OPCAO_SIMPLES CHAR(1) NOT NULL, 
	DATA_OPCAO_SIMPLES CHAR(8) NULL, 
	DATA_EXCLUSAO_SIMPLES CHAR(8) NULL,
	OPCAO_MEI CHAR(1) NOT NULL, 
	DATA_OPCAO_MEI CHAR(8) NULL, 
	DATA_EXCLUSAO_MEI CHAR(8) NULL,
	CONSTRAINT PK_SIMP PRIMARY KEY (CNPJ_BASICO)
);
-- OBS1: 
-- REMOVIDA: CONSTRAINT FK_EMPR_SIMP FOREIGN KEY (CNPJ_BASICO) REFERENCES cnpj.EMPRESA (CNPJ_BASICO)
-- MOTIVO: NA CARGA DE 20211014, OBSERVOU-SE 9 CASOS DE CNPJ_BASICO DE cnpj.SIMPLES SEM REFERENCIA EM cnpj.EMPRESA
-- (1) "24417449";"N";"20160318";"20160406";"N";"20160318";"20160406"
-- (2) "24539162";"N";"20160406";"20170308";"N";"20160406";"20170308"
-- (3) "30721933";"S";"20180618";"00000000";"S";"20180618";"00000000"
-- (4) "30728066";"S";"20180618";"00000000";"S";"20180618";"00000000"
-- (5) "30760363";"S";"20180621";"00000000";"S";"20180621";"00000000"
-- (6) "30847991";"S";"20180704";"00000000";"S";"20180704";"00000000"
-- (7) "30857441";"S";"20180705";"00000000";"S";"20180705";"00000000"
-- (8) "30886793";"S";"20180710";"00000000";"S";"20180710";"00000000"
-- (9) "30972017";"S";"20180719";"00000000";"S";"20180719";"00000000"

-- -----------------------------------------------
-- 5. ESTABELECIMENTO
-- -----------------------------------------------
-- 5.0. ESTABELECIMENTO
-- 5.1. MATRIZ_FILIAL
-- 5.2. SITUACAO_CADASTRAL
-- 5.3. ESTABELEC_CNAE_SECUNDARIA
-- -----------------------------------------------
CREATE TABLE cnpj.MATRIZ_FILIAL (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL, 	
	CONSTRAINT PK_MAFI PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.MATRIZ_FILIAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'MATRIZ', 0);
INSERT INTO cnpj.MATRIZ_FILIAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, 'FILIAL', 0);

CREATE TABLE cnpj.SITUACAO_CADASTRAL (
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL, 
	FLAG_CARGA_PELO_ETL INTEGER NOT NULL, 	
	CONSTRAINT PK_SICA PRIMARY KEY (CODIGO)
);
INSERT INTO cnpj.SITUACAO_CADASTRAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (1, 'NULA', 0);
INSERT INTO cnpj.SITUACAO_CADASTRAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (2, 'ATIVA', 0);
INSERT INTO cnpj.SITUACAO_CADASTRAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (3, 'SUSPENSA', 0);
INSERT INTO cnpj.SITUACAO_CADASTRAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (4, 'INAPTA', 0);
INSERT INTO cnpj.SITUACAO_CADASTRAL (CODIGO, DESCRICAO, FLAG_CARGA_PELO_ETL) VALUES (8, 'BAIXADA', 0);

CREATE TABLE cnpj.ESTABELECIMENTO (
	CNPJ_BASICO CHAR(8) NOT NULL,
	CNPJ_ORDEM CHAR(4) NOT NULL,
	CNPJ_DV CHAR(2) NOT NULL,
	COD_MATRIZ_FILIAL INTEGER NOT NULL,
	NOME_FANTASIA VARCHAR(255) NULL,
	COD_SITUACAO_CADASTRAL INTEGER NOT NULL,
	DATA_SITUACAO_CADASTRAL CHAR(8) NOT NULL,
	COD_MOTIVO_SITUACAO_CADASTRAL INTEGER NOT NULL,
	NOME_CIDADE_EXTERIOR VARCHAR(255) NULL,
	COD_PAIS INTEGER NULL,
	DATA_INICIO_ATIVIDADE CHAR(8) NOT NULL,
	COD_CNAE_PRINCIPAL INTEGER NOT NULL,
--	CNAE_SECUNDARIAS VARCHAR(4000) NULL,
	TIPO_LOGRADOURO VARCHAR(255) NULL,
	LOGRADOURO VARCHAR(255) NULL,
	NUMERO VARCHAR(255) NULL,
	COMPLEMENTO VARCHAR(255) NULL, 
	BAIRRO VARCHAR(255) NULL,
	CEP CHAR(8) NULL,
	UF CHAR(2) NULL,
	COD_MUNICIPIO INTEGER NULL,
	DDD_1 CHAR(2) NULL,
	TELEFONE_1 CHAR(9) NULL,
	DDD_2 CHAR(2) NULL,
	TELEFONE_2 CHAR(9) NULL,
	DDD_FAX CHAR(2) NULL,
	FAX CHAR(9) NULL,
	CORREIO_ELETRONICO VARCHAR(255) NULL,
	SITUACAO_ESPECIAL VARCHAR(255) NULL,
	DATA_SITUACAO_ESPECIAL CHAR(8) NULL,
	CONSTRAINT PK_ESTA PRIMARY KEY (CNPJ_BASICO, CNPJ_ORDEM), 
	CONSTRAINT FK_EMPR_ESTA FOREIGN KEY (CNPJ_BASICO) REFERENCES cnpj.EMPRESA (CNPJ_BASICO), 
	CONSTRAINT FK_MAFI_ESTA FOREIGN KEY (COD_MATRIZ_FILIAL) REFERENCES cnpj.MATRIZ_FILIAL (CODIGO), 
	CONSTRAINT FK_SICA_ESTA FOREIGN KEY (COD_SITUACAO_CADASTRAL) REFERENCES cnpj.SITUACAO_CADASTRAL (CODIGO), 
	CONSTRAINT FK_MOTI_ESTA FOREIGN KEY (COD_MOTIVO_SITUACAO_CADASTRAL) REFERENCES cnpj.MOTIVO_SITUACAO_CADASTRAL (CODIGO), 
	CONSTRAINT FK_CNAE_ESTA FOREIGN KEY (COD_CNAE_PRINCIPAL) REFERENCES cnpj.CNAE (CODIGO), 
	CONSTRAINT FK_MUNI_ESTA FOREIGN KEY (COD_MUNICIPIO) REFERENCES cnpj.MUNICIPIO (CODIGO)
);
-- OBS1:
-- REMOVIDA: CONSTRAINT FK_PAIS_ESTA FOREIGN KEY (COD_PAIS) REFERENCES cnpj.PAIS (CODIGO)
-- MOTIVO: CODIGOS SEM CORRESPONDÊNCIA NA LISTA DE PAISES DO SISCOMEX (http://www.siscomex.gov.br)

CREATE TABLE cnpj.ESTABELEC_CNAE_SECUNDARIA (
	CNPJ_BASICO CHAR(8) NOT NULL,
	CNPJ_ORDEM CHAR(4) NOT NULL,
	COD_CNAE INTEGER NOT NULL,
	CONSTRAINT PK_ESCS PRIMARY KEY (CNPJ_BASICO, CNPJ_ORDEM, COD_CNAE), 
	CONSTRAINT FK_ESTA_ESCS FOREIGN KEY (CNPJ_BASICO, CNPJ_ORDEM) REFERENCES cnpj.ESTABELECIMENTO (CNPJ_BASICO, CNPJ_ORDEM), 
	CONSTRAINT FK_CNAE_ESCS FOREIGN KEY (COD_CNAE) REFERENCES cnpj.CNAE (CODIGO)	
);
