-- -----------------------------------------------
-- 1. TABELAS AUXILIARES
-- -----------------------------------------------

-- -----------------------------------------------
-- 2. EMPRESA
-- -----------------------------------------------
CREATE INDEX IN_FK_NATJ_EMPR ON cnpj.EMPRESA (COD_NATUREZA_JURIDICA);
CREATE INDEX IN_FK_QUAL_EMPR_RESP ON cnpj.EMPRESA (COD_QUALIFICACAO_RESPONSAVEL);
CREATE INDEX IN_FK_PORT_EMPR ON cnpj.EMPRESA (COD_PORTE);

-- -----------------------------------------------
-- 3. SOCIO
-- -----------------------------------------------
CREATE INDEX IN_FK_EMPR_SOCI ON cnpj.SOCIO (CNPJ_BASICO);
CREATE INDEX IN_FK_TISO_SOCI ON cnpj.SOCIO (COD_TIPO);
CREATE INDEX IN_FK_QUAL_SOCI ON cnpj.SOCIO (COD_QUALIFICACAO);
CREATE INDEX IN_FK_QUAL_SOCI_REPR ON cnpj.SOCIO (COD_QUALIFICACAO_REPRESENTANTE);
CREATE INDEX IN_FK_FAET_SOCI ON cnpj.SOCIO (COD_FAIXA_ETARIA);

-- OBS1:
-- REMOVIDA: CONSTRAINT PK_SOCI PRIMARY KEY (CNPJ_BASICO, COD_TIPO, NOME, CNPJ_CPF)
-- MOTIVO: CASOS DE REPETICAO PARA COD_TIPO = 3 (ESTRANGEIRO)
-- Ex.1: 00205027; 3; DSC COMMUNICATIONS CORPORATION; <BRANCO> [DATA_ENTRADA_SOCIEDADE diferentes]
-- Ex.2: 01025206; 3; USTEST INC; <BRANCO> [CPF_REPRESENTANTE diferentes]
-- Ex.3: 00643187; 3; ROSEWOOK PARTNERS, INC.; <BRANCO> [2 linhas repetidas]
-- COMPLEMENTANDO A CRIACAO DE INDICES PARA OS CAMPOS NOME e CNPJ_CPF
CREATE INDEX IN_SOCI_NOME ON cnpj.SOCIO (NOME);
CREATE INDEX IN_SOCI_CNPJ_CPF ON cnpj.SOCIO (CNPJ_CPF);

-- OBS2:
-- REMOVIDA: CONSTRAINT FK_PAIS_SOCI FOREIGN KEY (COD_PAIS) REFERENCES cnpj.PAIS (CODIGO)
-- MOTIVO: CÓDIGOS SEM CORRESPONDÊNCIA NA LISTA DE PAÍSES DO SISCOMEX (http://www.siscomex.gov.br)
CREATE INDEX IN_SOCI_COD_PAIS ON cnpj.SOCIO (COD_PAIS);

-- -----------------------------------------------
-- 4. SIMPLES
-- -----------------------------------------------
CREATE INDEX IN_SIMP_OPCAO_SIMPLES ON cnpj.SIMPLES (OPCAO_SIMPLES);
CREATE INDEX IN_SIMP_OPCAO_MEI ON cnpj.SIMPLES (OPCAO_MEI);

-- -----------------------------------------------
-- 5. ESTABELECIMENTO
-- -----------------------------------------------
CREATE INDEX IN_FK_EMPR_ESTA ON cnpj.ESTABELECIMENTO (CNPJ_BASICO);
CREATE INDEX IN_FK_MAFI_ESTA ON cnpj.ESTABELECIMENTO (COD_MATRIZ_FILIAL);
CREATE INDEX IN_FK_SICA_ESTA ON cnpj.ESTABELECIMENTO (COD_SITUACAO_CADASTRAL);
CREATE INDEX IN_FK_MOTI_ESTA ON cnpj.ESTABELECIMENTO (COD_MOTIVO_SITUACAO_CADASTRAL);
CREATE INDEX IN_FK_CNAE_ESTA ON cnpj.ESTABELECIMENTO (COD_CNAE_PRINCIPAL);
CREATE INDEX IN_FK_MUNI_ESTA ON cnpj.ESTABELECIMENTO (COD_MUNICIPIO);
	
-- OBS1:
-- REMOVIDA: CONSTRAINT FK_PAIS_ESTA FOREIGN KEY (COD_PAIS) REFERENCES cnpj.PAIS (CODIGO)
-- MOTIVO: CODIGOS SEM CORRESPONDÊNCIA NA LISTA DE PAISES DO SISCOMEX (http://www.siscomex.gov.br)
CREATE INDEX IN_ESTA_COD_PAIS ON cnpj.ESTABELECIMENTO (COD_PAIS);

-- 5.3. ESTABELEC_CNAE_SECUNDARIA
CREATE INDEX IN_FK_ESTA_ESCS ON cnpj.ESTABELEC_CNAE_SECUNDARIA (CNPJ_BASICO, CNPJ_ORDEM);
CREATE INDEX IN_FK_CNAE_ESCS ON cnpj.ESTABELEC_CNAE_SECUNDARIA (COD_CNAE);
